<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import SocialBar from "./components/SocialBar";
import Splash from "./components/Splash";
import ScrollProgress from "./components/ScrollProgress";
=======
import type { Metadata } from "next"
import { Geist, Geist_Mono, IBM_Plex_Mono } from "next/font/google"
import Footer from "./components/Footer"
import Nav from "./components/Nav"
import ScrollProgress from "./components/ScrollProgress"
import SocialBar from "./components/SocialBar"
import Splash from "./components/Splash"
import { ThemeProvider } from "./components/theme-provider"
import "./globals.css"
>>>>>>> 55c0a3a (Added codes)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
<<<<<<< HEAD
});
=======
})
>>>>>>> 55c0a3a (Added codes)

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
<<<<<<< HEAD
});
=======
})
>>>>>>> 55c0a3a (Added codes)

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
<<<<<<< HEAD
});
=======
})
>>>>>>> 55c0a3a (Added codes)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
<<<<<<< HEAD
};
=======
}
>>>>>>> 55c0a3a (Added codes)

export default function RootLayout({
  children,
}: Readonly<{
<<<<<<< HEAD
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexMono.variable} antialiased bg-[#0A1930] text-slate-200`}
      >
        <div className="min-h-screen flex flex-col">
          <Splash />
          <Nav />
          <SocialBar />
          <ScrollProgress />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
=======
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexMono.variable} antialiased bg-background text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen flex flex-col">
            <Splash />
            <Nav />
            <SocialBar />
            <ScrollProgress />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
>>>>>>> 55c0a3a (Added codes)
}
